title: My Portfolio
description: A collection of my software engineering projects.
url: https://hammad123.github.io
baseurl: ""
theme: jekyll-theme-feeling-responsive

# Optional: Add your social media links
social_links:
  github: https://github.com/HQ786
  linkedin: https://www.linkedin.com/in/hammad-qadeer-1723bb265/
